### PR TITLE
Cell and can logger health checks

### PR DESCRIPTION
**Pull request by aaron97neu**
Additional health checks for a can and cell logger. Also moved all containers over to a `unless-stopped` restart policy as we discussed in a previous meeting

~Currently seeing a strange issue where the docker hub version does not seem to have been updated~ I'm dumb it works

### CODE REVIEW

**Comment by aaron97neu** [comment]
Can't verify can-logger because it does not work in it's current state but the code is almost identical to cell-logger so it should be alright. Screenshot of everything else working:
image

**Comment by facastiblancor** [comment]
> Can't verify can-logger because it does not work in it's current state but the code is almost identical to cell-logger so it should be alright. Screenshot of everything else working:
> image

That version of can-logger has issues with DB inserts, so that's probably the reason it is crashing. That issue has been solved and will be merged in an upcoming PR.

**Comment by aaron97neu** [comment]
Awaiting @facastiblancor's changes to the cell-logger so I can ensure my health checks are compatible with his changes to the cell-logger

**Comment by aaron97neu** [comment]
So merged master into this branch for testing and found that `can-logger` is unhealthy if there are messages appearing on one bus and no messages appearing on the other even if the logger itself is working fine. 

I am tempted to say that this situation is a configuration error and the unhealthy status is correct, but I could also watch the `rx_bytes` file and only check if that is incrementing. That would add some complexity as this should be stateless and I am not sure at the moment how to cheat that. Also at some point I am rewriting all of the logic in `can-logger` which kind of defeats the purpose of a simple health check

@facastiblancor thoughts?

**Comment by abalmos** [comment]
The implement bus may go long periods of time with nothing on it and then someone attach an implement with a controller.

**Comment by aaron97neu** [comment]
Good point. I'll plan on fixing this next week

**Comment by aaron97neu** [comment]
Tests look good on my end, this should be ready for review

**Review by facastiblancor — APPROVED** [review]
Looks good to me. Cell check is OK. Personally, I prefer the sleep approach on the CAN logger, as it has less footprint.

**Review by abalmos — APPROVED** [review]
Algo LGTM

**Pull request merged**
